version: 2

sources:  
  - name: airbnb_curation
    database: airbnb
    schema: curation_dev
    tables:
      - name: curation_hosts
        description: "Personne mettant en location des biens sur airbnb"
        columns:
          - name: host_id
            description: "Identifiant unique de l'hôte"
            tests:
               - unique
               - not_null
          - name: host_name
            description: "Nom de l'hôte"
            tests:
               - not_null
          - name: host_since
            description: "Date d'inscription de l'hôte"
            tests:
               - not_null
          - name: host_location
            description: "Ville et pays de l'hôte"
            tests:
               - not_null
          - name: host_city
            description: "Ville l'hôte"
            tests:
               - not_null
          - name: host_country
            description: "pays de l'hôte"
            tests:
               - not_null
          - name : response_rate
            description: "taux de réponse de l'hôte"
          - name: is_superhost
            description: "Indicateur si l'hôte a le statut superhost"
            tests:
               - not_null
               - accepted_values:
                   arguments:
                     values: ['t', 'f']
          - name: is_identity_verified
            description: "Indicateur si l'identité de l'hôte a été vérifiée"
            tests:
              - not_null
              - accepted_values:
                  arguments:
                     values: ['t', 'f']


      - name: curation_listings
        description: "description d'un bien en location sur airbnb"
        columns:
          - name: listing_id
            description: "identifiant unique de la presention"
            tests:
              - not_null
              - unique
          - name: listing_url
            description: "url de la présentation"
            tests:
              - not_null
              - unique
          - name: name
            description: "nom de la présentation"
            tests:
              - not_null
          - name: description
            description: "description de la location -- i.e la présentation en elle_même"
          - name: has_description
            description : "Possede ou pas une description"
            tests:
              - not_null 
              - accepted_values:
                  arguments:
                     values: [TRUE, FALSE]
                     quote: FALSE 
          - name: neighbourhood_overview
            description: "descritption rapide du quartier"
          - name: has_neighbourhood_description
            description: "possede une description rapide du quartier"
            tests:
              - not_null
              - accepted_values:
                  arguments:
                     values: [TRUE, FALSE]
                     quote: FALSE 
          - name: host_id
            description: "identifiant de l'hote qui met en location le bien décrit dans cette présentation"
            tests:
               - dbt_utils.relationships_where:
                    arguments:
                        to: ref('curation_hosts')
                        field: host_id
          - name: neighbourhood_cleansed
            description: "quartier"
            tests:
              - not_null
          - name: latitude
            description: "coordonnée du bien : latitude"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  arguments:
                    min_value: -90.0
                    max_value : 90.0 
                    inclusive: true 
          - name: longitude
            description: "coordonnée du bien : longitude"
            tests:
               - not_null 
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: -180.0
                    max_value: 180.0
                    inclusive: true         
          - name: property_type
            description: "type de bien mis en location"
            tests:
               - not_null
          - name: room_type
            description: "type de pièce du bien mis en location"
            tests:
               - not_null
          - name: accommodates
            description: "capacité d'accueil"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 1
                    inclusive: true 
          - name: bathrooms
            description: "nombre de salles de bain"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: true 
          - name: bedrooms
            description: "nombre de chambres"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: true
          - name: amenities
            description: "équipements"
            tests:
               - not_null
          - name: price
            description: "tarif de la location"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: false
          - name: minimum_nights
            description: "nombre de nuités minimum"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: false 
          - name: maximum_nights
            description: "nombre de nuités maximum"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: false

      - name: curation_reviews
        description: "date d'un avis"
        columns:
          - name: listing_id
            description: " l'annonce sur laquelle porte cet avis"
            tests:
               - dbt_utils.relationships_where:
                  arguments:
                      to: ref('curation_listings')
                      field: listing_id
          - name: review_date
            description: " date de l'avis"
            tests:
               - not_null
               
      - name: curation_tourists_per_year
        description: "tourist par annee "
        columns:
          - name: year
            description: "la date"
            tests:
              - not_null
              - unique
          - name: tourists
            description: "nombre de touriste"
            tests:
              - not_null
              
              

unit_tests:
  - name: test_is_host_data_transformation_correct
    description: "Vérifie que host_name, host_city, host_country et response_rate sont créés correctement"
    model: curation_hosts
    given:
      - input: ref('hosts_snapshot')
        rows:
          - {host_name: 'Jacko', host_location: "ville,pays", host_response_rate: '32%', DBT_VALID_TO: null, host_id: 'host_id', host_since: '2026-01-01',host_is_superhost: 't',host_identity_verified: 't'} 
          - {host_name: 'Xi', host_location: "ville,pays", host_response_rate: '32.03%', DBT_VALID_TO: null,  host_id: 'host_id', host_since: '2026-01-01',host_is_superhost: 't',host_identity_verified: 't'}
          - {host_name: 'J', host_location: "pays,ville", host_response_rate: '32.53%', DBT_VALID_TO: null,  host_id: 'host_id', host_since: '2026-01-01',host_is_superhost: 't',host_identity_verified: 't'}
    expect:
      rows:
        - {host_name: 'Jacko', host_city: 'ville', host_country: 'pays', response_rate: 32}
        - {host_name: 'Xi', host_city: 'ville', host_country: 'pays', response_rate: 32}
        - {host_name: 'Anonyme', host_city: 'pays', host_country: 'ville', response_rate: 33}

  - name: test_is_listening_data_transformation_correct
    description: "Vérifie que le prix est bien créé correctement"
    model: curation_listings
    given:
      - input: ref('curation_hosts')
        rows: 
            - {host_id : 'host_id'}
      - input: ref("listings_snapshot")
        rows: 
            - {price : '$3.12', DBT_VALID_TO: NULL, id: 'id1', listing_url: 'https://adresse1', name: 'nom', host_id: 'host_id', neighbourhood_cleansed: 'quartier', longitude: 180, latitude: -90.0, property_type: 'type', room_type: 'type', accommodates: 1, bathrooms: 2, bedrooms: 2,  amenities: 'amenties', minimum_nights: 1, maximum_nights: 1}  
            - {price : '$0.12', DBT_VALID_TO: NULL,  id: 'id2', listing_url: 'https://adresse2', name: 'nom', host_id: 'host_id', neighbourhood_cleansed: 'quartier', longitude: 180, latitude: -90.0, property_type: 'type', room_type: 'type', accommodates: 1, bathrooms: 2, bedrooms: 2, amenities: 'amenties', minimum_nights: 1, maximum_nights: 1}  
            - {price : '$3.0', DBT_VALID_TO: NULL, id: 'id3', listing_url: 'https://adresse3', name: 'nom', host_id: 'host_id', neighbourhood_cleansed: 'quartier', longitude: 180, latitude: -90.0, property_type: 'type', room_type: 'type', accommodates: 1, bathrooms: 2, bedrooms: 2,  amenities: 'amenties', minimum_nights: 1, maximum_nights: 1}  
            - {price : '$123,333.0', DBT_VALID_TO: NULL, id: 'id4', listing_url: 'https://adresse3', name: 'nom', host_id: 'host_id', neighbourhood_cleansed: 'quartier', longitude: 180, latitude: -90.0, property_type: 'type', room_type: 'type', accommodates: 1, bathrooms: 2, bedrooms: 2,  amenities: 'amenties', minimum_nights: 1, maximum_nights: 1}  
    expect:
        rows:
            - {listing_id: 'id1', price: 3.12} 
            - {listing_id: 'id2',price: 0.12} 
            - {listing_id: 'id3',price: 3}              
            - {listing_id: 'id4',price: 123333} 

  - name: test_is_reviews_data_transformation_correct
    description: "Vérifie l'agrégation quotidienne des reviews par listing_id"
    model: curation_reviews
    given:
      - input: ref('curation_listings')
        rows:
          - {listing_id: 'listing_1'}
          - {listing_id: 'listing_2'}
      - input: ref('reviews_snapshot')
        rows:
          # Ligne valide
          - {listing_id: 'listing_1', date: '2025-01-15', DBT_VALID_TO: null}
          - {listing_id: 'listing_1', date: '2025-01-15', DBT_VALID_TO: null}  # 2 reviews même jour
          - {listing_id: 'listing_1', date: '2025-01-16', DBT_VALID_TO: null}
          # Ligne valide : autre listing
          - {listing_id: 'listing_2', date: '2025-01-15', DBT_VALID_TO: null}
    expect:
          rows:
            - {listing_id: 'listing_1', review_date: '2025-01-15', number_reviews: 2}
            - {listing_id: 'listing_1', review_date: '2025-01-16', number_reviews: 1}
            - {listing_id: 'listing_2', review_date: '2025-01-15', number_reviews: 1}
  - name: test_is_tourist_per_year_data_transformation_correct
    description: "Vérifie que l'année est bien créé correctement"
    model: curation_tourists_per_year
    given:
      - input: ref("tourists_per_year")
        rows: 
            - {year : '2025'}
    expect:
        rows:
          - {year: '2025-12-31'}
  


