version: 2

sources:
  - name: raw_airbnb_data
    database: airbnb
    schema: raw
    tables:
      - name: hosts
        description: "Personne mettant en location des biens sur airbnb"
        columns:
          - name: host_id
            description: "Identifiant unique de l'hôte"
            tests:
               - unique
               - not_null
          - name: host_name
            description: "Nom de l'hôte"
            tests:
               - not_null
          - name: host_since
            description: "Date d'inscription de l'hôte"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: '1900-01-01'
                    max_value: "current_date()"
          - name: host_location
            description: "Ville et pays de l'hôte"
            tests:
               - not_null
          - name: host_is_superhost
            description: "Indicateur si l'hôte a le statut superhost"
            tests:
               - not_null
               - accepted_values:
                   arguments:
                     values: ['t', 'f']
          - name: host_neighbourhood
            description: "Quartier de l'hôte"
            tests:
               - not_null
          - name: host_identity_verified
            description: "Indicateur si l'identité de l'hôte a été vérifiée"
            tests:
               - not_null
               - accepted_values:
                   arguments:
                     values: ['t', 'f']

      - name: listings
        description: "description d'un bien en location sur airbnb"
        columns:
          - name: id
            description: "identifiant unique de la presention"
            tests:
               - not_null
               - unique
          - name: listing_url
            description: "url de la présentation"
            tests:
               - not_null
               - unique
          - name: name
            description: "nom de la présentation"
            tests:
               - not_null
          - name: description
            description: "description de la location -- i.e la présentation en elle_même"
            tests:
               - not_null
          - name: neighbourhood_overview
            description: "descritption rapide du quartier"
            tests:
               - not_null
          - name: host_id
            description: "identifiant de l'hote qui met en location le bien décrit dans cette présentation"
            tests:
                - dbt_utils.relationships_where:
                    arguments:
                        to: ref('host')
                        field: host_id
          - name: latitude
            description: "coordonnée du bien : latitude"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: -90.0
                    max_value: 90.0
                    inclusive: true 
          - name: longitude
            description: "coordonnée du bien : longitude"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: -180.0
                    max_value: 180
                    inclusive: true 
          - name: property_type
            description: "type de bien mis en location"
            tests:
               - not_null
          - name: room_type
            description: "type de pièce du bien mis en location"
            tests:
               - not_null
          - name: accomodates
            description: "capacité d'accueil"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  arguments:
                    min_value: 1
                    inclusive: true 
          - name: bathrooms
            description: "nombre de salles de bain"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: true 
          - name: bedrooms
            description: "nombre de chambres"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: true 
          - name: beds
            description: "nombre de lit"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: true 
          - name: amenities
            description: "équipements"
            tests:
               - not_null
          - name: price
            description: "tarif de la location"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: false 
          - name: minimum_nights
            description: "nombre de nuités minimum"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: 0
                    inclusive: false 
          - name: maximum_nights
            description: "nombre de nuités maximum"
            tests:
               - not_null

      - name: reviews
        description: "date d'un avis"
        columns:
          - name: listing_id
            description: " l'annonce sur laquelle porte cet avis"
            tests:
               - dbt_utils.relationships_where:
                  arguments:
                      to: ref('listings')
                      field: host_id
          - name: date
            description: " date de l'avis"
            tests:
               - not_null
               - dbt_utils.accepted_range:
                  arguments:
                    min_value: '1900-01-01'
                    max_value: "current_date()"
